name: CI

on: [push, pull_request]

env:
  FORCE_COLOR: 2

jobs:
  test:
    name: Node
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Test
        run: npm test
        
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
